I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2.rpy", line 282, in script
    if obey == True:
  File "game/script2.rpy", line 282, in <module>
    if obey == True:
NameError: name 'obey' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2.rpy", line 282, in script
    if obey == True:
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script2.rpy", line 282, in <module>
    if obey == True:
NameError: name 'obey' is not defined

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
3 More Days 1.1
Mon Apr 21 17:50:26 2025
