I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "game/screens.rpy", line 14, in <module>
    language gui.language()
TypeError: 'str' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/main.py", line 652, in main
    run(restart)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/main.py", line 75, in run
    renpy.translation.init_translation()
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/translation/__init__.py", line 702, in init_translation
    renpy.store._init_language() # type: ignore
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/translation/__init__.py", line 796, in change_language
    new_change_language(tl, language)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/translation/__init__.py", line 748, in new_change_language
    i.apply()
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/ast.py", line 2800, in apply
    value = renpy.python.py_eval(expr)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens.rpy", line 14, in <module>
    language gui.language()
TypeError: 'str' object is not callable

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
3 More Days 1.2
Sun Jun  1 18:16:24 2025
