I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 788, in script
    $ finn == True
  File "game/script.rpy", line 788, in <module>
    $ finn == True
NameError: name 'finn' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 788, in script
    $ finn == True
  File "/Volumes/renpy-8.3.3-sdk 1/renpy-8.3.3-sdk/renpy/ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Volumes/renpy-8.3.3-sdk 1/renpy-8.3.3-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 788, in <module>
    $ finn == True
NameError: name 'finn' is not defined

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
5 More Days 1.0
Wed Feb 12 01:02:38 2025
